name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get app name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          REPO_NAME=${{ github.event.repository.name }}
          
          # Check if the branch name is "master"
          if [ $BRANCH_NAME = "master" ]; then
            APP_NAME=$REPO_NAME
          else
            APP_NAME="${REPO_NAME}_${BRANCH_NAME}"
          fi
          
          echo "APP_NAME=$APP_NAME" >> vars.env
          echo $APP_NAME

      - name: Generate random number
        run: |
          PORT=$((RANDOM % (65000 - 5000 + 1) + 5000))
          
          echo "PORT=$PORT" >> vars.env
          echo "PROJECT_NAME=${{ github.event.repository.name }}" >> vars.env

  clean:
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Remove container and image
        run: |
          source vars.env
          export PORT=$PORT
          if docker inspect $APP_NAME > /dev/null 2>&1; then docker rm -f $APP_NAME && docker rmi -f $APP_NAME; else echo "Container not found."; fi

  build:
    runs-on: self-hosted
    needs: clean
    steps:
      - name: Build docker image
        run: |
          source vars.env
          docker build --tag $APP_NAME . 

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run docker container
        run: |
          source vars.env
          
          docker run --name $APP_NAME -d \
            --network zoo \
            -e PORT=$PORT -p $PORT:$PORT \
             $APP_NAME